# GrowDesk V2 Docker Compose

services:
  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: growdesk-api-gateway
    ports:
      - "80:80"    
      - "8082:8082" 
    volumes:
      - ./api-gateway/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./api-gateway/dynamic_conf:/etc/traefik/dynamic_conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - grow-network
    environment:
      - TRAEFIK_PROVIDERS_DOCKER_NETWORK=growdeskv2_grow-network
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
      - widget-api
      - widget-core
      - demo-site

  # GrowDesk Core Services
  postgres:
    image: postgres:15
    container_name: growdesk-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: growdesk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./GrowDesk/backend/internal/db/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - grow-network

  redis:
    image: redis:7
    container_name: growdesk-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - grow-network

  backend:
    build:
      context: ./GrowDesk/backend
      dockerfile: Dockerfile
    container_name: growdesk-backend
    ports:
      - "8081:8080"  
    networks:
      - grow-network
    environment:
      - PORT=8080
      - DATA_DIR=/app/data
      - MOCK_AUTH=true
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=growdesk
      - USE_POSTGRES=true
      - MIGRATE_DATA=true
      - REDIS_HOST=redis
      - SYNC_SERVICE_URL=http://sync-server:8000/api/sync
      - WIDGET_API_URL=http://growdesk-widget-api:3000
      - JWT_SECRET=super_secret_jwt_key_change_in_production
      - ALLOWED_ORIGINS=http://localhost:3001,http://localhost:80,http://localhost:3030,http://localhost:8090
    volumes:
      - backend_data:/app/data
      - ./GrowDesk/backend/.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 40s
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  sync-server:
    build:
      context: ./GrowDesk/backend
      dockerfile: Dockerfile.sync
    container_name: growdesk-sync-server
    ports:
      - "8001:8000"  
    volumes:
      - backend_data:/app/data
      - ./GrowDesk/backend/data:/backend/data
    environment:
      - PORT=8000
      - DATA_DIR=/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 40s
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./GrowDesk/frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    container_name: growdesk-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./GrowDesk/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost/api 
      - VITE_SYNC_API_URL=http://localhost/api/sync/users  
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      - grow-network
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  # GrowDesk Widget Services
  widget-api:
    build:
      context: ./GrowDesk-Widget/widget-api
      dockerfile: Dockerfile
    container_name: growdesk-widget-api
    ports:
      - "3002:3000"
    volumes:
      - ./GrowDesk-Widget/widget-api:/app
      - ./GrowDesk-Widget/widget-api/data:/app/data
      - ./GrowDesk-Widget/.env:/app/.env
    environment:
      - PORT=3000
      - DATA_DIR=/app/data
      - GROWDESK_API_URL=http://growdesk-backend:8080
      - GROWDESK_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJ3aWRnZXQtYXBpLXN5c3RlbSIsImVtYWlsIjoid2lkZ2V0QGdyb3dkZXNrLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc2NzIzNTIwMCwiaWF0IjoxNzM1Njk5MjAwfQ.K8vF2nJ9mP4qR6sT3uV7wX1yZ5aB8cD0eF2gH4iJ6kL
      - WIDGET_BASE_URL=http://growdesk-widget-core:3030  
      - GIN_MODE=debug
      - JWT_SECRET=clave_secreta_desarrollo_local
      - ALLOWED_ORIGINS=http://localhost,http://localhost:80,http://localhost:3001,http://localhost:3030,http://localhost:8090,http://localhost:4321,http://localhost:4322,http://vidriera-web:4321
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=growdesk
      - USE_POSTGRES=true
      - MIGRATE_DATA=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - grow-network
    depends_on:
      postgres:
        condition: service_healthy
      backend:
        condition: service_started

  widget-core:
    build:
      context: ./GrowDesk-Widget/widget-core
      dockerfile: Dockerfile
    container_name: growdesk-widget-core
    ports:
      - "3031:3030"  
    volumes:
      - ./GrowDesk-Widget/widget-core:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3030
      - WIDGET_API_URL=http://localhost/widget-api 
    restart: unless-stopped
    networks:
      - grow-network
    depends_on:
      widget-api:
        condition: service_started

  demo-site:
    build:
      context: ./GrowDesk-Widget/examples/simple-demo
      dockerfile: Dockerfile
    container_name: growdesk-demo-site
    ports:
      - "8091:8090"  
    volumes:
      - ./GrowDesk-Widget/examples/simple-demo:/app
      - /app/node_modules
    depends_on:
      widget-core:
        condition: service_started
      widget-api:
        condition: service_started
    environment:
      - PORT=8090
      - NODE_ENV=development
      - WIDGET_CORE_URL=http://localhost/widget 
      - WIDGET_API_URL=http://localhost/widget-api  
    restart: unless-stopped
    networks:
      - grow-network

  # Vidriera Web (Cristales del Valle)
  vidriera-web:
    build:
      context: ./Vidriera-Web/frontend
      dockerfile: Dockerfile
    container_name: cristales-del-valle-web
    ports:
      - "4321:4321"
    depends_on:
      widget-api:
        condition: service_started
      widget-core:
        condition: service_started
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - grow-network

networks:
  grow-network:
    driver: bridge

volumes:
  postgres_data:
  backend_data:
  backend_uploads: 